### ISSUE TITLE
TypeError: img should be PIL Image. Got <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by MatchaYa9** [donglgcn/ADA-VAD#1]
您好，我在运行您代码的过程中遇到了一些问题，需要您的帮助
python unetonlyInfomaxAnypredictStage1.py -f .cfgs/unetonlyAnypredictStage1/***
我使用该指令运行的过程中出现了TypeError: img should be PIL Image. Got <class 'torch.Tensor'>
请问我该如何解决

**Comment by MatchaYa9** [comment]
transform = transforms.Compose([
    # transforms.Resize((32,32)),
    transforms.ToTensor(),
])我删除掉 transforms.Resize((32,32)),该行代码就可以运行，请问这是什么问题

**Comment by donglgcn** [comment]
您好，感谢您的关注，我可以在未改变代码的情况下运行。你可以先试试将resize删除进行试验，目前我没有找到可能有影响的地方。不过理论上transform.Resize可以接受PIL或者tensor类型的输入https://pytorch.org/vision/0.13/generated/torchvision.transforms.functional.resize.html ，您可以检查一下torchvision的版本是否一致，0.13+。
如果您后续有其他问题也欢迎联系。
